# This is an example docker-compose file

version: "3.5"

services:
  tinfluxweatherstation:
    image: akeusen/tinfluxws:latest
    container_name: tinfluxws
    restart: always
    environment:
      - TINFLUXWS_STATIONNAME=myWeatherStationName
      - TINFLUXWS_MASTERBRICK_HOST=masterb.domain.local
      - TINFLUXWS_MASTERBRICK_PORT=4223
      - TINFLUXWS_INFLUXDB_HOST_URI=https://influxhost.domain.local:443
      - TINFLUXWS_INFLUXDB_NAME=myInfluxDB
      
    # Because of security reasons, the following env variables should be placed in a separate .env file.
    # Even better use Docker secrets: https://docs.docker.com/engine/swarm/secrets/
    # - TINFLUXWS_INFLUXDB_USER=
    # - TINFLUXWS_INFLUXDB_PASSWD=
    
  # env_file:
    # - ./docker.env
    
    secrets:
      - influxuser
      - influxpassword

# File based docker secrets (if not in swarm mode):
secrets:
  influxuser:
    file: ./dbusername
  influxpassword:
    file: ./dbpassword
