# This is an example docker-compose file

version: "3.5"

services:
  tinfluxweatherstation:
    image: akeusen/tinfluxws:latest
    container_name: tinfluxws
    restart: always
    environment:
      - TRIFLUXWS_STATIONNAME=myWeatherStationName
      - TRIFLUXWS_MASTERBRICK_HOST=masterb.domain.local
      - TRIFLUXWS_MASTERBRICK_PORT=4223
      - TRIFLUXWS_INFLUXDB_HOST_URI=https://influxhost.domain.local:443
      - TRIFLUXWS_INFLUXDB_NAME=myInfluxDB
      
    # Because of security reasons, the following env variables should be placed in a separate .env file.
    # Even better use Docker secrets: https://docs.docker.com/engine/swarm/secrets/
    # - TRIFLUXWS_INFLUXDB_USER=
    # - TRIFLUXWS_INFLUXDB_PASSWD=
    
  # env_file:
    # - ./docker.env
    
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
